@extends('admin.layouts.app')
@section('title', 'Affiliate Program')
@section('content')
<x-admin.page-header title="Affiliate Program" :breadcrumb="[['label' => 'Marketing'], ['label' => 'Affiliates']]" />
@include('admin.affiliates._nav')
<div class="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">@foreach(['pending','approved','rejected','suspended'] as $status)<a href="{{ route('admin.affiliates.index', ['status' => $status]) }}" class="admin-card p-5"><p class="text-xs uppercase text-gray-400">{{ $status }}</p><p class="mt-2 text-2xl font-semibold">{{ $counts[$status] ?? 0 }}</p></a>@endforeach</div>
<form class="mb-5 flex flex-col gap-3 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="Name or email" class="admin-input"><select name="status" class="admin-input"><option value="">All statuses</option>@foreach(\App\Models\AffiliateProfile::STATUSES as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="admin-btn-primary">Filter</button></form>
<div class="admin-card overflow-x-auto"><table class="admin-table min-w-full"><thead><tr><th>Affiliate</th><th>Code</th><th>Status</th><th>Clicks</th><th>Orders</th><th>Applied</th><th></th></tr></thead><tbody>@forelse($affiliates as $affiliate)<tr><td><p class="font-medium">{{ $affiliate->user->name }}</p><p class="text-xs text-gray-400">{{ $affiliate->user->email }}</p></td><td class="font-mono text-xs">{{ $affiliate->referral_code }}</td><td class="capitalize">{{ $affiliate->status }}</td><td>{{ $affiliate->clicks_count }}</td><td>{{ $affiliate->orders_count }}</td><td>{{ $affiliate->applied_at->format('d M Y') }}</td><td><a href="{{ route('admin.affiliates.show', $affiliate) }}" class="text-champagne-dark hover:underline">Manage</a></td></tr>@empty<tr><td colspan="7" class="py-10 text-center text-gray-400">No affiliates found.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $affiliates->links() }}</div>
@endsection
