@extends('admin.layouts.app')
@section('title', 'Manage Affiliate')
@section('content')
<x-admin.page-header :title="$affiliate->user->name" :breadcrumb="[['label' => 'Affiliates', 'url' => route('admin.affiliates.index')], ['label' => $affiliate->referral_code]]" />
@include('admin.affiliates._nav')
<div class="grid gap-6 xl:grid-cols-3"><div class="space-y-6 xl:col-span-2">
<div class="admin-card p-6"><div class="grid gap-4 sm:grid-cols-2"><div><p class="text-xs text-gray-400">Email</p><p>{{ $affiliate->user->email }}</p></div><div><p class="text-xs text-gray-400">Phone</p><p>{{ $affiliate->user->phone ?: '—' }}</p></div><div><p class="text-xs text-gray-400">Website</p><p class="break-all">{{ $affiliate->website_url ?: '—' }}</p></div><div><p class="text-xs text-gray-400">Social profile</p><p class="break-all">{{ $affiliate->social_url ?: '—' }}</p></div></div><div class="mt-5 border-t pt-5"><p class="text-xs text-gray-400">Application</p><p class="mt-1 whitespace-pre-line text-sm">{{ $affiliate->application_message }}</p></div></div>
<div class="admin-card overflow-x-auto"><table class="admin-table min-w-full"><thead><tr><th>Bucket</th><th>Amount</th></tr></thead><tbody>@foreach($wallet as $bucket => $amount)<tr><td class="capitalize">{{ $bucket }}</td><td>₹{{ number_format($amount, 2) }}</td></tr>@endforeach</tbody></table></div>
<div class="admin-card overflow-x-auto"><div class="p-5 font-semibold">Recent ledger entries</div><table class="admin-table min-w-full"><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Available Δ</th></tr></thead><tbody>@foreach($recentLedger as $entry)<tr><td>{{ $entry->occurred_at->format('d M Y') }}</td><td>{{ str_replace('_',' ',$entry->type) }}</td><td>{{ $entry->description }}</td><td>₹{{ number_format($entry->available_delta, 2) }}</td></tr>@endforeach</tbody></table></div>
</div><div class="space-y-6"><form method="POST" action="{{ route('admin.affiliates.status', $affiliate) }}" class="admin-card space-y-4 p-6">@csrf @method('PATCH')<h2 class="font-semibold">Review & commission</h2><x-admin.form.select label="Status" name="status" :value="$affiliate->status" :options="array_combine(\App\Models\AffiliateProfile::STATUSES, array_map('ucfirst', \App\Models\AffiliateProfile::STATUSES))" /><x-admin.form.input label="Affiliate-specific rate (%)" name="commission_rate" type="number" min="0" max="100" step="0.01" :value="$affiliate->commission_rate" help="Overrides product, category and Global rules for this affiliate. Leave blank to use the applicable rules; an active Global rule is required for approval." /><x-admin.form.textarea label="Admin notes" name="admin_notes" :value="$affiliate->admin_notes" :rows="4" /><button class="admin-btn-primary w-full">Save</button></form>
@if($affiliate->payoutAccount)<div class="admin-card p-6"><h2 class="font-semibold">Payout account</h2><dl class="mt-4 space-y-2 text-sm"><div><dt class="text-gray-400">Method</dt><dd class="uppercase">{{ $affiliate->payoutAccount->payout_method }}</dd></div>@if($affiliate->payoutAccount->payout_method === 'bank')<div><dt class="text-gray-400">Account</dt><dd>Ending {{ $affiliate->payoutAccount->account_last_four }}</dd></div><div><dt class="text-gray-400">IFSC</dt><dd>{{ $affiliate->payoutAccount->ifsc }}</dd></div>@else<div><dt class="text-gray-400">UPI</dt><dd>{{ $affiliate->payoutAccount->upi_id }}</dd></div>@endif</dl><form method="POST" action="{{ route('admin.affiliates.payout-verification', $affiliate) }}" class="mt-4">@csrf @method('PATCH')<input type="hidden" name="is_verified" value="{{ $affiliate->payoutAccount->is_verified ? 0 : 1 }}"><button class="admin-btn-secondary w-full">{{ $affiliate->payoutAccount->is_verified ? 'Remove verification' : 'Mark verified' }}</button></form></div>@endif</div></div>
@endsection
