@extends('admin.layouts.app')
@section('title', 'Affiliate Withdrawals')
@section('content')
<x-admin.page-header title="Withdrawal Queue" :breadcrumb="[['label' => 'Affiliates', 'url' => route('admin.affiliates.index')], ['label' => 'Withdrawals']]" />@include('admin.affiliates._nav')
<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Manual payout mode is active. Never mark a withdrawal paid until the bank/UPI transfer is confirmed. A processing request stays reserved during uncertain provider or bank timeouts.</div>
<form class="mb-5 flex gap-3"><select name="status" class="admin-input"><option value="">All statuses</option>@foreach(\App\Models\AffiliateWithdrawal::STATUSES as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="admin-btn-primary">Filter</button></form>
<div class="space-y-4">@forelse($withdrawals as $row)<div class="admin-card p-5"><div class="flex flex-col justify-between gap-4 lg:flex-row"><div><p class="font-semibold">{{ $row->request_reference }} · {{ $row->affiliate->user->name }}</p><p class="mt-1 text-sm text-gray-500">Gross ₹{{ number_format($row->gross_amount, 2) }} · deduction ₹{{ number_format($row->deduction_amount, 2) }} · net ₹{{ number_format($row->net_amount, 2) }}</p><p class="mt-1 text-xs text-gray-400">{{ $row->status }} / reconciliation: {{ $row->reconciliation_status }} / requested {{ $row->requested_at->format('d M Y H:i') }}</p></div>
@if(in_array($row->status, ['requested','approved','processing']))@php($nextStatuses = match($row->status) { 'requested' => ['approved','rejected'], 'approved' => ['processing','rejected'], default => ['paid','failed'] })<form method="POST" action="{{ route('admin.affiliates.withdrawals.update', $row) }}" class="grid min-w-0 gap-2 sm:grid-cols-2 lg:w-[520px]">@csrf @method('PATCH')<select name="status" class="admin-input">@foreach($nextStatuses as $status)<option value="{{ $status }}">{{ ucfirst($status) }}</option>@endforeach</select><input name="transfer_reference" placeholder="Transfer UTR/reference (paid)" class="admin-input"><input name="failure_reason" placeholder="Failure reason (failed)" class="admin-input"><input name="admin_notes" placeholder="Admin note" class="admin-input"><button class="admin-btn-primary sm:col-span-2">Update withdrawal</button></form>@else<div class="text-sm font-semibold capitalize">{{ $row->status }}{{ $row->transfer_reference ? ' · '.$row->transfer_reference : '' }}</div>@endif</div></div>@empty<div class="admin-card p-10 text-center text-gray-400">No withdrawals.</div>@endforelse</div><div class="mt-5">{{ $withdrawals->links() }}</div>
@endsection
